### ISSUE TITLE
Ignore `_site/` files 

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/quarto-clinic#2]
How do we get Git to ignore `_site/ ...html, txt, json, xml` files? 
The live site looks fine without committing these.

.gitignore:
```
.Rproj.user
.Rhistory
.RData
.Ruserdata

/.quarto/
*_cache/
_site/

.DS_Store
```

my RStudio git pane
![Screenshot 2024-05-10 at 1 01 25 PM](https://github.com/Openscapes/quarto-clinic/assets/11927811/5e455dc3-69eb-4e34-a962-ba3007f33b3f)

**Comment by ateucher** [comment]
This is very likely because the `_site` directory was committed at one point in the past, before it was added to `.gitignore`.  Git will keep track of files that it has previously tracked even after they've been ignored. 

This should fix it:

_First make sure there are no uncommitted files, then_:

```
# remove files from git's index (but leave them on your disk)
git rm -r --cached _site

git add .

git commit -m "stop tracking _site/ dir"

git push
```

**Comment by stefaniebutland** [comment]
Thanks Andy! That deleted a fair few `_site/` files. Looking forward to them being ignored in my next set of edits
